name: Bug Report
description: File a bug/issue
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** _Before_ reporting an issue, make sure to read the [README](https://github.com/loqusion/hyprshade).
  - type: checkboxes
    attributes:
      label: Did you check the docs?
      description: Make sure you have checked all of the below before submitting an issue.
      options:
        - label: I have read the entire README.
          required: true
        - label: I did not manually copy any configuration or shader files from the repository.
          required: true
  - type: dropdown
    attributes:
      label: Installation method
      description: How you installed Hyprshade
      options:
        - AUR - `hyprshade`
        - AUR - `hyprshade-git`
        - Nixpkgs
        - "`pipx`"
        - Other (describe below)
      default: 4
  - type: input
    attributes:
      label: Other installation method
      description: If you picked "Other" for installation method above, please describe.
    validations:
      required: false
  - type: input
    attributes:
      label: Linux distribution
      placeholder: Arch Linux
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Please include any related error messages. If possible, try re-running any relevant `hyprshade` commands with the `--verbose` flag passed, e.g. `hyprshade --verbose on blue-light-filter`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Configuration
      description: The contents of your configuration file, if you have one (either located at `~/.config/hypr/hyprshade.toml` or `~/.config/hyprshade/config.toml`).
      render: toml
    validations:
      required: false
